name: Add GitHub release version to Jira issues

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  call-jira-sync:
    name: Call Jira versions update
    uses: reportportal/.github/.github/workflows/update-jira-versions.yaml@5d208acab22207a12d6b204373dc76b97d61bf8c
    with:
      jira-server: ${{ vars.JIRA_SERVER }}
    secrets:
      JIRA_TOKEN: ${{ secrets.JIRA_TOKEN }}
